### ISSUE TITLE
[BUG]: Subscriptable objects doesn't seem to work

### ISSUE THREAD

**Issue by bontchev** [xakepnz/enterpriseattack#13]
### What happened?

Using the example from the documentation:

```python
import enterpriseattack
attack = enterpriseattack.Attack(subscriptable=True)
wizard_spider = attack.groups.get('Wizard Spider')
```
results in the error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'get'
```

### Version

0.1.6

**Comment by xakepnz** [comment]
Hi @bontchev, thanks for reporting. Looks like my build and publish for `0.1.6` was missing the wheel.

**Before:**
<img width="1196" alt="Screen Shot 2022-12-28 at 9 16 43 PM" src="https://user-images.githubusercontent.com/26149256/209781559-a8ac2a9f-5de5-44af-b0a3-1d6668fc8524.png">

**After:**
<img width="1214" alt="Screen Shot 2022-12-28 at 9 16 55 PM" src="https://user-images.githubusercontent.com/26149256/209781590-634a258e-f56f-44d3-97c4-b541489187b5.png">

Which means pip would've grabbed `0.1.5` instead, and that feature was not available....

Please try the following:
```
pip install --no-cache enterpriseattack==0.1.6
```
Confirm you're using `0.1.6`:
```
>>> import enterpriseattack
>>> enterpriseattack.__version__
'0.1.6'
```
Then retry:
```
>>> attack = enterpriseattack.Attack(subscriptable=True)
>>> wizard_spider = attack.groups.get('Wizard Spider')
```

**Comment by bontchev** [comment]
You are right, `pip` had actually installed version `0.1.5`. I have updated to version `0.1.7` and the problem has disappeared. Closing the issue now.
